language: r
sudo: false
cache: packages

r-packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(token = "05a70b7e-5496-4099-bab8-8b89008cab63" )'

notifications:
  email:
    on_success: change
    on_failure: change
